#!/bin/bash
 
version=0.1

chmod 755 scripts/*
scripts/init_kitchen
scripts/check_binaries

result=$?
if [ "$result" == "1" ]
then
  exit 0
fi

while :
do

 clear

 echo 
 echo "============================================================"
 echo " SGS Android Kitchen $version - by RMGeren (xda-developers.com)"
 echo
 echo "        Based on the HTC Android Kitchen - by dsixda" 
 echo "============================================================"
 echo
 echo "  1 - Set up working folder from ROM"
 echo "  2 - Add root permissions"
 echo "  3 - Add BusyBox"
 echo "  4 - Disable boot screen sounds"
 echo "  5 - Zipalign all *.apk files to optimize RAM usage"
 echo "  6 - Change wipe status of ROM"
 echo "  7 - Change name of ROM"
 echo "  8 - Check update-script for errors"
 echo "  9 - Show working folder information"
 echo " 10 - Set up working folder for Samsung leak"
 echo 
 echo "  0 - ADVANCED OPTIONS"
 echo " 99 - Build ROM from working folder"
 echo
 echo "  u - Update/About kitchen"
 echo "  x - Exit"
 echo ""
 echo -n "Enter option: "
 read opt
 case $opt in
   1) clear; scripts/check_rom; continue;;
   2) scripts/do_root; continue;;
   3) scripts/add_busybox show_help;;
   4) scripts/disable_sounds;;
   5) scripts/do_zipalign;;
   6) scripts/change_wipe;;
   7) scripts/change_rom_name;;
   8) scripts/verify_update_script; continue;;
   9) scripts/show_rom_info;;
  10) clear; scripts/choose_rom_rfs; continue;;
   0) scripts/menu_advanced $version; continue;;
   99) scripts/build_rom;;
   u) scripts/about $version; continue;;
   x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
   *) echo "Invalid option"; continue;;
 esac

  scripts/press_enter

done
